build:
	g++ -c main.cpp
	g++ main.o -o game -lsfml-graphics -lsfml-window -lsfml-system -L/usr/local/lib -ltmxlite
build-and-run:
	g++ -c main.cpp
	g++ main.o -o game -lsfml-graphics -lsfml-window -lsfml-system -L/usr/local/lib -ltmxlite 
	./game